### ISSUE TITLE
Cygwin build: undefined reference to `__imp_libfsapfs_notify_set_stream'

### ISSUE THREAD

**Issue by fossilet** [libyal/libfsapfs#31] opened 2020-09-03 02:31 UTC
My setup:

- OS: Windows 10 2004
- Cygwin packages:
  - autoconf: 13-1
  - automake: 11-1
  - binutils: 2.34-1
  - gcc-core: 9.3.0-2
  - gcc-g++: 9.3.0-2 (make error if not present)
  - gettext: 0.19.8.1-2
  - libiconv: 1.16-2
  - libssl-devel: 1.1.1f-1
  - libtool: 2.4.6-7
  - make: 4.3-1
  - pkg-config: 1.6.3-1
  - zlib-devel: 1.2.11-1

configure options:
`./configure --enable-verbose-output --enable-debug-output`

Without verbose and debug options, similar errors are produced.

Full make error log:
[make-error.log](https://github.com/libyal/libfsapfs/files/5165806/make-error.log)

**Comment by joachimmetz** [comment] 2020-09-03 03:28
The issue does not surface in the Cygwin CI builds https://ci.appveyor.com/project/libyal/libfsapfs

* which version of libfsapfs are you building?
* how did you download the libfsapfs (git or source distribution package)?
* can you attach config.log

**Comment by fossilet** [comment] 2020-09-03 08:13
Tried git code from the appveyor setup:

```
./synclibs.sh --use-head
 ./autogen.sh
 ./configure --enable-verbose-output --enable-debug-output
make
```
Get similar errors: [make-error-git.txt](https://github.com/libyal/libfsapfs/files/5167143/make-error-git.txt).

**Comment by joachimmetz** [comment] 2020-09-03 08:26
I would need to take a closer look when time permits why Cygwin is being unable to find libfsapfs_notify_set_stream. This likely has to do with DLL import/export not being set correctly in your build configuration.

**Comment by joachimmetz** [comment] 2020-11-07 14:57
I did a ,anual build with latest libfsapfs on latest Cygwin 64-bit without any issues.

> libfsapfs version: libfsapfs-experimental-20200727

However your config says 20200802 ?

```
| #define PACKAGE_TARNAME "libfsapfs"
| #define PACKAGE_VERSION "20200802"
```

DLL import/export look correctly configured

```
ac_cv_enable_wide_character_type=no
ac_cv_enable_winapi=no

LIBFSAPFS_DLL_EXPORT='-DLIBFSAPFS_DLL_EXPORT'
LIBFSAPFS_DLL_IMPORT='-DLIBFSAPFS_DLL_IMPORT'
```

Do you maybe have an unclean build environment that is causing you grief?

Also web search for "relocation truncated to fit: R_X86_64_PC32 against undefined symbol" there are multiple different reasons why this error is given.

**Comment by joachimmetz** [comment] 2020-11-07 14:59
Ah wait the other config.log says

```
| #define PACKAGE_VERSION "20200727"
| #define PACKAGE_STRING "libfsapfs 20200727"

LIBFSAPFS_DLL_EXPORT='-DLIBFSAPFS_DLL_EXPORT'
LIBFSAPFS_DLL_IMPORT='-DLIBFSAPFS_DLL_IMPORT'
```

**Comment by joachimmetz** [comment] 2020-11-07 15:03
I suspect this is something in with your build environment. I'll close this issue since I cannot reproduce it.

**Closed by joachimmetz** 2020-11-07 15:03 UTC
