### ISSUE TITLE
MacOS 'openssl/err.h' file not found 

### ISSUE THREAD

**Issue by glitchtracker** [libyal/libfsapfs#65] opened 2022-12-30 09:56 UTC
Hi, 
the make process fails here
libcaes_context.c:31:10: fatal error: 'openssl/err.h' file not found

M1 Mac Ventura 13.0.1

**Comment by joachimmetz** [comment] 2022-12-30 10:14
Likely duplicate of https://github.com/libyal/libfsapfs/issues/56

**Comment by glitchtracker** [comment] 2022-12-30 13:50
Well I tried to install brew openss 1.1 and it didn't work
I guess that's because there's still OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022) when invoking 
openssl version

But I'm a bit affraid to change that to 1.1 as it may be used by mac os. What to do ?

**Comment by joachimmetz** [comment] 2022-12-30 15:58
The issue is not the version of openssl, the issue is that configure is not able to find all the necessary information to use openssl on your system/installation. Make sure CPPFLAGS, CFLAGS, LDFLAGS and PATH are set correctly. Alternatively tell configure where to find openssl or disable it. config.log typically contains relevant information.

**Comment by joachimmetz** [comment] 2023-01-04 17:07
No update from original reporter, considering question answered.

**Closed by joachimmetz** 2023-01-04 17:07 UTC
Labels: duplicate, question
